### ISSUE TITLE
metadata?

### ISSUE THREAD

**Issue by ianbstewart** [leondz/emerging_entities_17#5]
Is there any metadata associated with the raw text (e.g. tweet ID, timestamp)? I could only find the raw text data.

**Comment by leondz** [comment]
Sadly (and surprisingly) this was not retained. If I find it, it'll be posted, but the prognosis is "no" :(

**Comment by ianbstewart** [comment]
OK. I figured that it would have to be removed for privacy, but just wanted to check. Thanks!
